/**
 * Comprehensive Dataset for SOL Global / US-DZ Airlift & Livestock Trace System
 * 109 Transatlantic Flights, Purebred Holstein Herd, Climate & Feed Matrix
 */

import { AirliftShipment, LivestockCow, ClimateTelemetry, FeedRationRecipe, QrPassportPayload } from '../types';

export const INITIAL_AIRLIFT_SHIPMENTS: AirliftShipment[] = [
  {
    id: 'flight_tx_001',
    flightNumber: 'SOL-AF-109-TX01',
    flightBatchIndex: 1,
    originAirport: {
      code: 'DFW',
      name: 'Dallas Fort Worth Int.',
      state: 'Texas',
      coordinates: [32.8998, -97.0403],
    },
    destinationAirport: {
      code: 'AZR',
      name: 'Adrar Touat Cheikh Sidi Mohamed Belkebir Airport',
      wilaya: 'Adrar',
      coordinates: [27.8383, -0.1864],
    },
    destinationFarm: {
      farmId: 'DZ-FARM-ADRAR-01',
      name: 'Adrar Mega-Dairy Oasis Complex (مشروع أدرار الاستراتيجي)',
      wilaya: 'Adrar',
      coordinates: [27.9124, -0.2241],
    },
    aircraftModel: 'Boeing 747-400F Cargo (Livestock Config)',
    departureTime: '2026-09-25T14:30:00Z',
    estimatedArrivalTime: '2026-09-26T03:15:00Z',
    status: 'quarantine_holding',
    quarantineStage: 'farm_quarantine_30d',
    headCount: 280,
    usdaHealthCertNumber: 'USDA-APHIS-2026-DZ-TX901',
    usdaVerifiedBy: 'Dr. Marcus Vance, DVM (USDA APHIS Area Director)',
    usdaVerificationDate: '2026-09-24',
    usdaStatus: 'verified',
    quarantineRemainingHours: 648, // ~27 days
    cabinTelemetry: {
      ambientTempC: 16.4,
      relativeHumidityPct: 53.2,
      airChangeRatePerHour: 34.0,
      oxygenLevelPct: 20.8,
      co2LevelPpm: 680,
    },
    mortalityRatePct: 0.000,
    notes: 'Flawless flight transit over the Atlantic. 280 purebred pregnant heifers transferred safely to Adrar quarantine biocontainment pen A1.',
  },
  {
    id: 'flight_tx_002',
    flightNumber: 'SOL-AF-109-TX02',
    flightBatchIndex: 2,
    originAirport: {
      code: 'IAH',
      name: 'Houston George Bush Intercontinental',
      state: 'Texas',
      coordinates: [29.9902, -95.3368],
    },
    destinationAirport: {
      code: 'BSK',
      name: 'Biskra Mohamed Khider International Airport',
      wilaya: 'Biskra',
      coordinates: [34.7933, 5.7383],
    },
    destinationFarm: {
      farmId: 'DZ-FARM-BISKRA-01',
      name: 'Ziban Agro-Dairy Basin Complex (مجمع الزيبان بسكرة)',
      wilaya: 'Biskra',
      coordinates: [34.8512, 5.7891],
    },
    aircraftModel: 'Boeing 777F Livestock Freighter',
    departureTime: '2026-09-26T18:00:00Z',
    estimatedArrivalTime: '2026-09-27T06:45:00Z',
    status: 'landed',
    quarantineStage: 'airport_primary_48h',
    headCount: 295,
    usdaHealthCertNumber: 'USDA-APHIS-2026-DZ-TX902',
    usdaVerifiedBy: 'Dr. Sarah Jenkins, DVM (APHIS Port Veterinary Officer)',
    usdaVerificationDate: '2026-09-25',
    usdaStatus: 'verified',
    quarantineRemainingHours: 42,
    cabinTelemetry: {
      ambientTempC: 16.8,
      relativeHumidityPct: 56.1,
      airChangeRatePerHour: 32.5,
      oxygenLevelPct: 20.7,
      co2LevelPpm: 710,
    },
    mortalityRatePct: 0.000,
    notes: 'Landed at Biskra BSK at 06:42Z. Undergoing primary 48-hour blood serology and thermal biometric inspection at airport hangar.',
  },
  {
    id: 'flight_az_003',
    flightNumber: 'SOL-AF-109-AZ03',
    flightBatchIndex: 3,
    originAirport: {
      code: 'PHX',
      name: 'Phoenix Sky Harbor International',
      state: 'Arizona',
      coordinates: [33.4352, -112.0101],
    },
    destinationAirport: {
      code: 'ALG',
      name: 'Houari Boumediene Airport Algiers',
      wilaya: 'Mila',
      coordinates: [36.6910, 3.2154],
    },
    destinationFarm: {
      farmId: 'DZ-FARM-MILA-01',
      name: 'Mila High Plains Dairy Hub (مشروع الهضاب العليا ميلة)',
      wilaya: 'Mila',
      coordinates: [36.4502, 6.2644],
    },
    aircraftModel: 'Boeing 747-400F Cargo',
    departureTime: '2026-09-27T10:15:00Z',
    estimatedArrivalTime: '2026-09-27T23:30:00Z',
    status: 'in_flight',
    quarantineStage: 'airport_primary_48h',
    headCount: 285,
    usdaHealthCertNumber: 'USDA-APHIS-2026-DZ-AZ903',
    usdaVerifiedBy: 'Dr. Robert Hensley, DVM (USDA Southwest Region)',
    usdaVerificationDate: '2026-09-26',
    usdaStatus: 'verified',
    quarantineRemainingHours: 48,
    cabinTelemetry: {
      ambientTempC: 15.9,
      relativeHumidityPct: 52.0,
      airChangeRatePerHour: 36.0,
      oxygenLevelPct: 20.9,
      co2LevelPpm: 640,
    },
    mortalityRatePct: 0.000,
    notes: 'Mid-Atlantic transit waypoint (FL350, 485 kts). Cabin environmental controls fully stabilized.',
  },
  {
    id: 'flight_nm_004',
    flightNumber: 'SOL-AF-109-NM04',
    flightBatchIndex: 4,
    originAirport: {
      code: 'ABQ',
      name: 'Albuquerque International Sunport',
      state: 'New Mexico',
      coordinates: [35.0402, -106.6092],
    },
    destinationAirport: {
      code: 'AZR',
      name: 'Adrar Touat Airport',
      wilaya: 'Adrar',
      coordinates: [27.8383, -0.1864],
    },
    destinationFarm: {
      farmId: 'DZ-FARM-ADRAR-01',
      name: 'Adrar Mega-Dairy Oasis Complex',
      wilaya: 'Adrar',
      coordinates: [27.9124, -0.2241],
    },
    aircraftModel: 'Boeing 747-400F Cargo',
    departureTime: '2026-09-28T02:00:00Z',
    estimatedArrivalTime: '2026-09-28T15:20:00Z',
    status: 'boarding',
    quarantineStage: 'airport_primary_48h',
    headCount: 290,
    usdaHealthCertNumber: 'USDA-APHIS-2026-DZ-NM904',
    usdaVerifiedBy: 'Dr. Elena Chavez, DVM (USDA NM District)',
    usdaVerificationDate: '2026-09-26',
    usdaStatus: 'verified',
    quarantineRemainingHours: 48,
    cabinTelemetry: {
      ambientTempC: 17.0,
      relativeHumidityPct: 54.0,
      airChangeRatePerHour: 33.0,
      oxygenLevelPct: 20.9,
      co2LevelPpm: 660,
    },
    mortalityRatePct: 0.000,
    notes: 'Boarding livestock pens in specialized climate cargo stalls at Sunport cargo ramp.',
  },
  {
    id: 'flight_tx_005',
    flightNumber: 'SOL-AF-109-TX05',
    flightBatchIndex: 5,
    originAirport: {
      code: 'DFW',
      name: 'Dallas Fort Worth Int.',
      state: 'Texas',
      coordinates: [32.8998, -97.0403],
    },
    destinationAirport: {
      code: 'BSK',
      name: 'Biskra Mohamed Khider Airport',
      wilaya: 'Biskra',
      coordinates: [34.7933, 5.7383],
    },
    destinationFarm: {
      farmId: 'DZ-FARM-BISKRA-01',
      name: 'Ziban Agro-Dairy Basin Complex',
      wilaya: 'Biskra',
      coordinates: [34.8512, 5.7891],
    },
    aircraftModel: 'Boeing 777F Livestock Freighter',
    departureTime: '2026-09-29T08:00:00Z',
    estimatedArrivalTime: '2026-09-29T20:30:00Z',
    status: 'scheduled',
    quarantineStage: 'airport_primary_48h',
    headCount: 300,
    usdaHealthCertNumber: 'USDA-APHIS-2026-DZ-TX905',
    usdaVerifiedBy: 'Dr. Marcus Vance, DVM',
    usdaVerificationDate: '2026-09-27',
    usdaStatus: 'pending_audit',
    quarantineRemainingHours: 48,
    cabinTelemetry: {
      ambientTempC: 16.5,
      relativeHumidityPct: 55.0,
      airChangeRatePerHour: 32.0,
      oxygenLevelPct: 20.9,
      co2LevelPpm: 650,
    },
    mortalityRatePct: 0.000,
    notes: 'Pre-flight veterinary isolation and blood serology check completed at Texas export facility.',
  },
];

export const INITIAL_LIVESTOCK: LivestockCow[] = [
  {
    id: 'cow_9021',
    rfidTag: 'RFID-CTL-9021',
    usEarTag: 'USA-TX-2024-8849',
    dzNationalId: 'DZ-ADR-01-9021',
    breed: 'Purebred Holstein Friesian',
    airliftShipmentId: 'flight_tx_001',
    flightNumber: 'SOL-AF-109-TX01',
    birthDate: '2024-03-15',
    originState: 'Texas',
    currentWilaya: 'Adrar',
    farmId: 'DZ-FARM-ADRAR-01',
    farmName: 'Adrar Mega-Dairy Oasis Complex (مشروع أدرار الاستراتيجي)',
    barnNumber: 'Barn-A (Desert Climate Controlled)',
    penNumber: 'Pen-04',
    quarantineStatus: 'quarantine_holding',
    quarantineDay: 4,
    geneticMerit: {
      sireName: 'Pine-Tree Dairy Kingpin-ET (TR TP TY TV TL)',
      sireRegistration: 'HOUSA72851652',
      damName: 'Lone-Star Superstition 4402',
      geneticMeritTpi: 2985,
      milkYieldGenomicPotentialL: 14200,
      genomicInbreedingPct: 4.1,
    },
    currentWeightKg: 642.5,
    weightHistory: [
      { date: '2026-09-01', weightKg: 631.0 },
      { date: '2026-09-15', weightKg: 638.0 },
      { date: '2026-09-24', weightKg: 640.5 },
      { date: '2026-09-27', weightKg: 642.5 },
    ],
    lactationCycle: {
      lactationNumber: 1,
      daysInMilk: 52,
      inseminationDate: '2026-08-10',
      inseminationBull: 'S-S-I Franchise Gallantry',
      pregnancyStatus: 'confirmed_pregnant',
      expectedCalvingDate: '2027-05-18',
    },
    averageMilkYieldL: 36.8,
    targetMilkYieldL: 38.0,
    recentMilkYields: [
      {
        date: '2026-09-25',
        morningYieldL: 14.5,
        noonYieldL: 10.2,
        eveningYieldL: 11.8,
        totalDailyYieldL: 36.5,
        fatPct: 3.84,
        proteinPct: 3.26,
        somaticCellCountK: 115,
        electricalConductivityMs: 4.8,
      },
      {
        date: '2026-09-26',
        morningYieldL: 14.8,
        noonYieldL: 10.6,
        eveningYieldL: 11.6,
        totalDailyYieldL: 37.0,
        fatPct: 3.88,
        proteinPct: 3.29,
        somaticCellCountK: 110,
        electricalConductivityMs: 4.7,
      },
      {
        date: '2026-09-27',
        morningYieldL: 14.7,
        noonYieldL: 10.4,
        eveningYieldL: 11.7,
        totalDailyYieldL: 36.8,
        fatPct: 3.86,
        proteinPct: 3.27,
        somaticCellCountK: 108,
        electricalConductivityMs: 4.7,
      },
    ],
    vaccinations: [
      {
        id: 'vac_01',
        date: '2026-09-10',
        vaccineName: 'Brucella Abortus Strain 19 (USDA Certified)',
        batchNumber: 'BRU-TX-2026-44',
        veterinarian: 'Dr. Marcus Vance, DVM',
        nextBoosterDate: '2027-09-10',
        status: 'valid',
      },
      {
        id: 'vac_02',
        date: '2026-09-12',
        vaccineName: 'Foot-and-Mouth Inactivated Vaccine (O/A/SAT2)',
        batchNumber: 'FMD-APHIS-991',
        veterinarian: 'Dr. Marcus Vance, DVM',
        nextBoosterDate: '2027-03-12',
        status: 'valid',
      },
      {
        id: 'vac_03',
        date: '2026-09-26',
        vaccineName: 'BVD & IBR Respiratory Complex',
        batchNumber: 'BOV-DZ-2601',
        veterinarian: 'Dr. Yassine Benali (Algerian Veterinary Inspector)',
        nextBoosterDate: '2027-09-26',
        status: 'administered',
      },
    ],
    healthScore: 97,
    ruminationMinutesPerDay: 540,
    activityIndex: 104,
    gpsCoordinates: [27.9124, -0.2241],
  },
  {
    id: 'cow_9022',
    rfidTag: 'RFID-CTL-9022',
    usEarTag: 'USA-TX-2024-8850',
    dzNationalId: 'DZ-ADR-01-9022',
    breed: 'Purebred Holstein Friesian',
    airliftShipmentId: 'flight_tx_001',
    flightNumber: 'SOL-AF-109-TX01',
    birthDate: '2024-03-18',
    originState: 'Texas',
    currentWilaya: 'Adrar',
    farmId: 'DZ-FARM-ADRAR-01',
    farmName: 'Adrar Mega-Dairy Oasis Complex',
    barnNumber: 'Barn-A (Desert Climate Controlled)',
    penNumber: 'Pen-04',
    quarantineStatus: 'quarantine_holding',
    quarantineDay: 4,
    geneticMerit: {
      sireName: 'De-Su 11236 Balisto-ET',
      sireRegistration: 'HOUSA70625988',
      damName: 'Lone-Star Massey 4210',
      geneticMeritTpi: 2910,
      milkYieldGenomicPotentialL: 13800,
      genomicInbreedingPct: 3.9,
    },
    currentWeightKg: 655.0,
    weightHistory: [
      { date: '2026-09-01', weightKg: 645.0 },
      { date: '2026-09-15', weightKg: 651.0 },
      { date: '2026-09-27', weightKg: 655.0 },
    ],
    lactationCycle: {
      lactationNumber: 1,
      daysInMilk: 60,
      inseminationDate: '2026-07-28',
      inseminationBull: 'S-S-I Franchise Gallantry',
      pregnancyStatus: 'confirmed_pregnant',
      expectedCalvingDate: '2027-05-05',
    },
    averageMilkYieldL: 38.4,
    targetMilkYieldL: 38.0,
    recentMilkYields: [
      {
        date: '2026-09-25',
        morningYieldL: 15.2,
        noonYieldL: 11.0,
        eveningYieldL: 12.0,
        totalDailyYieldL: 38.2,
        fatPct: 3.91,
        proteinPct: 3.32,
        somaticCellCountK: 98,
        electricalConductivityMs: 4.6,
      },
      {
        date: '2026-09-26',
        morningYieldL: 15.4,
        noonYieldL: 11.2,
        eveningYieldL: 12.1,
        totalDailyYieldL: 38.7,
        fatPct: 3.93,
        proteinPct: 3.34,
        somaticCellCountK: 95,
        electricalConductivityMs: 4.6,
      },
      {
        date: '2026-09-27',
        morningYieldL: 15.3,
        noonYieldL: 11.0,
        eveningYieldL: 12.1,
        totalDailyYieldL: 38.4,
        fatPct: 3.90,
        proteinPct: 3.31,
        somaticCellCountK: 92,
        electricalConductivityMs: 4.6,
      },
    ],
    vaccinations: [
      {
        id: 'vac_04',
        date: '2026-09-10',
        vaccineName: 'Brucella Abortus Strain 19',
        batchNumber: 'BRU-TX-2026-44',
        veterinarian: 'Dr. Marcus Vance, DVM',
        nextBoosterDate: '2027-09-10',
        status: 'valid',
      },
      {
        id: 'vac_05',
        date: '2026-09-12',
        vaccineName: 'Foot-and-Mouth Inactivated Vaccine',
        batchNumber: 'FMD-APHIS-991',
        veterinarian: 'Dr. Marcus Vance, DVM',
        nextBoosterDate: '2027-03-12',
        status: 'valid',
      },
    ],
    healthScore: 99,
    ruminationMinutesPerDay: 565,
    activityIndex: 110,
    gpsCoordinates: [27.9126, -0.2238],
  },
  {
    id: 'cow_9023',
    rfidTag: 'RFID-CTL-9023',
    usEarTag: 'USA-AZ-2024-5112',
    dzNationalId: 'DZ-BSK-01-9023',
    breed: 'Purebred Holstein Friesian',
    airliftShipmentId: 'flight_tx_002',
    flightNumber: 'SOL-AF-109-TX02',
    birthDate: '2024-02-28',
    originState: 'Arizona',
    currentWilaya: 'Biskra',
    farmId: 'DZ-FARM-BISKRA-01',
    farmName: 'Ziban Agro-Dairy Basin Complex (مجمع الزيبان بسكرة)',
    barnNumber: 'Barn-02 (Evaporative Pad Cooled)',
    penNumber: 'Pen-12',
    quarantineStatus: 'quarantine_holding',
    quarantineDay: 2,
    geneticMerit: {
      sireName: 'Melarry Mogul Frazzled-ET',
      sireRegistration: 'HOUSA74261651',
      damName: 'Desert-Star Supersire 771',
      geneticMeritTpi: 2950,
      milkYieldGenomicPotentialL: 14000,
      genomicInbreedingPct: 4.4,
    },
    currentWeightKg: 628.0,
    weightHistory: [
      { date: '2026-09-01', weightKg: 620.0 },
      { date: '2026-09-20', weightKg: 626.0 },
      { date: '2026-09-27', weightKg: 628.0 },
    ],
    lactationCycle: {
      lactationNumber: 1,
      daysInMilk: 38,
      inseminationDate: '2026-08-15',
      inseminationBull: 'S-S-I Franchise Gallantry',
      pregnancyStatus: 'inseminated_monitoring',
    },
    averageMilkYieldL: 34.2,
    targetMilkYieldL: 36.0,
    recentMilkYields: [
      {
        date: '2026-09-27',
        morningYieldL: 13.8,
        noonYieldL: 9.6,
        eveningYieldL: 10.8,
        totalDailyYieldL: 34.2,
        fatPct: 3.79,
        proteinPct: 3.22,
        somaticCellCountK: 125,
        electricalConductivityMs: 4.9,
      },
    ],
    vaccinations: [
      {
        id: 'vac_06',
        date: '2026-09-08',
        vaccineName: 'Brucella Abortus Strain 19',
        batchNumber: 'BRU-AZ-2026-11',
        veterinarian: 'Dr. Sarah Jenkins, DVM',
        nextBoosterDate: '2027-09-08',
        status: 'valid',
      },
      {
        id: 'vac_07',
        date: '2026-09-10',
        vaccineName: 'Foot-and-Mouth Inactivated Vaccine',
        batchNumber: 'FMD-APHIS-991',
        veterinarian: 'Dr. Sarah Jenkins, DVM',
        nextBoosterDate: '2027-03-10',
        status: 'valid',
      },
    ],
    healthScore: 94,
    ruminationMinutesPerDay: 510,
    activityIndex: 98,
    gpsCoordinates: [34.8512, 5.7891],
  },
  {
    id: 'cow_9024',
    rfidTag: 'RFID-CTL-9024',
    usEarTag: 'USA-NM-2024-3011',
    dzNationalId: 'DZ-MLA-01-9024',
    breed: 'Purebred Holstein Friesian',
    airliftShipmentId: 'flight_az_003',
    flightNumber: 'SOL-AF-109-AZ03',
    birthDate: '2024-04-02',
    originState: 'New Mexico',
    currentWilaya: 'Mila',
    farmId: 'DZ-FARM-MILA-01',
    farmName: 'Mila High Plains Dairy Hub (مشروع الهضاب العليا ميلة)',
    barnNumber: 'Barn-M1',
    penNumber: 'Pen-01',
    quarantineStatus: 'quarantine_holding',
    quarantineDay: 1,
    geneticMerit: {
      sireName: 'Mr Mogul Delta 1427-ET',
      sireRegistration: 'HOUSA72128216',
      damName: 'Rio-Grande Dairy Queen 902',
      geneticMeritTpi: 3015,
      milkYieldGenomicPotentialL: 14500,
      genomicInbreedingPct: 4.0,
    },
    currentWeightKg: 660.0,
    weightHistory: [
      { date: '2026-09-01', weightKg: 650.0 },
      { date: '2026-09-20', weightKg: 658.0 },
      { date: '2026-09-27', weightKg: 660.0 },
    ],
    lactationCycle: {
      lactationNumber: 1,
      daysInMilk: 72,
      inseminationDate: '2026-07-14',
      inseminationBull: 'Pine-Tree Dairy Kingpin',
      pregnancyStatus: 'confirmed_pregnant',
      expectedCalvingDate: '2027-04-20',
    },
    averageMilkYieldL: 39.5,
    targetMilkYieldL: 40.0,
    recentMilkYields: [
      {
        date: '2026-09-27',
        morningYieldL: 15.8,
        noonYieldL: 11.5,
        eveningYieldL: 12.2,
        totalDailyYieldL: 39.5,
        fatPct: 3.95,
        proteinPct: 3.36,
        somaticCellCountK: 85,
        electricalConductivityMs: 4.5,
      },
    ],
    vaccinations: [
      {
        id: 'vac_08',
        date: '2026-09-05',
        vaccineName: 'Brucella Abortus Strain 19',
        batchNumber: 'BRU-NM-2026-02',
        veterinarian: 'Dr. Elena Chavez, DVM',
        nextBoosterDate: '2027-09-05',
        status: 'valid',
      },
      {
        id: 'vac_09',
        date: '2026-09-07',
        vaccineName: 'Foot-and-Mouth Inactivated Vaccine',
        batchNumber: 'FMD-APHIS-991',
        veterinarian: 'Dr. Elena Chavez, DVM',
        nextBoosterDate: '2027-03-07',
        status: 'valid',
      },
    ],
    healthScore: 98,
    ruminationMinutesPerDay: 580,
    activityIndex: 112,
    gpsCoordinates: [36.4502, 6.2644],
  },
];

export const WILAYAS_CLIMATE: ClimateTelemetry[] = [
  {
    wilaya: 'Adrar',
    ambientTempC: 38.6,
    relativeHumidityPct: 18.0,
    thi: 79.2, // Moderate to Severe Stress without cooling
    stressCategory: 'severe_stress',
    windSpeedKmh: 14.5,
    solarRadiationWm2: 890,
    timestamp: '2026-09-27T17:55:00Z',
    predictedDropInMilkLiters: 3.4,
  },
  {
    wilaya: 'Biskra',
    ambientTempC: 34.2,
    relativeHumidityPct: 32.0,
    thi: 73.6, // Moderate Stress
    stressCategory: 'moderate_stress',
    windSpeedKmh: 11.2,
    solarRadiationWm2: 820,
    timestamp: '2026-09-27T17:55:00Z',
    predictedDropInMilkLiters: 1.8,
  },
  {
    wilaya: 'Mila',
    ambientTempC: 26.4,
    relativeHumidityPct: 48.0,
    thi: 64.3, // Normal comfort zone
    stressCategory: 'normal',
    windSpeedKmh: 9.8,
    solarRadiationWm2: 640,
    timestamp: '2026-09-27T17:55:00Z',
    predictedDropInMilkLiters: 0.0,
  },
  {
    wilaya: 'El Oued',
    ambientTempC: 36.8,
    relativeHumidityPct: 24.0,
    thi: 76.4, // Moderate to Severe
    stressCategory: 'moderate_stress',
    windSpeedKmh: 13.0,
    solarRadiationWm2: 860,
    timestamp: '2026-09-27T17:55:00Z',
    predictedDropInMilkLiters: 2.5,
  },
];

export const SAMPLE_FEED_RATIONS: Record<string, FeedRationRecipe> = {
  Adrar: {
    wilaya: 'Adrar',
    thiIndex: 79.2,
    targetDailyYieldL: 38.0,
    ingredients: [
      {
        nameAr: 'دريس البرسيم الحجازي الممتاز (Alfalfa Hay)',
        nameEn: 'Premium Alfalfa Hay (High Fiber & Quality Protein)',
        amountKgDay: 7.5,
        dryMatterPct: 90.0,
        crudeProteinPct: 20.5,
        netEnergyMcal: 1.48,
        purpose: 'مصدر رئيسي للألياف الفعالة NDF وتحفيز الاجترار أثناء درجات الحرارة المرتفعة',
      },
      {
        nameAr: 'سيلاج الذرة عالي الطاقة (Corn Silage)',
        nameEn: 'Corn Silage (High Starch & Moisture)',
        amountKgDay: 18.0,
        dryMatterPct: 35.0,
        crudeProteinPct: 8.2,
        netEnergyMcal: 1.62,
        purpose: 'طاقة نشوية بطيئة التحلل تحافظ على نشاط الكرش وتوفر السوائل الطبيعية',
      },
      {
        nameAr: 'كسب فول الصويا 48% (Soybean Meal)',
        nameEn: 'Soybean Meal (48% Crude Protein)',
        amountKgDay: 3.8,
        dryMatterPct: 89.0,
        crudeProteinPct: 48.0,
        netEnergyMcal: 1.95,
        purpose: 'بروتين غير متحلل بالكرش (RUP) عالي الكفاءة لإنتاج كازين الحليب',
      },
      {
        nameAr: 'بذور القطن الكاملة (Whole Cottonseed)',
        nameEn: 'Whole Cottonseed (Energy & Digestible Fiber)',
        amountKgDay: 2.2,
        dryMatterPct: 91.0,
        crudeProteinPct: 23.0,
        netEnergyMcal: 2.10,
        purpose: 'دهون طبيعية وألياف دون رفع حرارة التخمر الباطني',
      },
      {
        nameAr: 'الدهون المحمية المهدرجة (Bypass Fat)',
        nameEn: 'Rumen-Protected Bypass Fat (Prilled)',
        amountKgDay: 0.65,
        dryMatterPct: 99.0,
        crudeProteinPct: 0.0,
        netEnergyMcal: 4.80,
        purpose: 'تعويض كثافة الطاقة بدون توليد حرارة أيضية داخل الكرش لمنع هبوط الإنتاج',
      },
    ],
    waterRequirementLitersDay: 155, // High desert water consumption
    activeCoolingProtocol: {
      mistingIntervalSeconds: 45,
      fanSpeedPct: 100,
      sprinklerFrequencyMinutes: 3,
      nighttimeHyperVentilation: true,
    },
    rumenBufferGramsDay: 280, // High bicarb buffer to prevent acidosis in extreme heat
  },
  Biskra: {
    wilaya: 'Biskra',
    thiIndex: 73.6,
    targetDailyYieldL: 36.0,
    ingredients: [
      {
        nameAr: 'برسيم حجازي جاف (Alfalfa Hay)',
        nameEn: 'Alfalfa Hay',
        amountKgDay: 6.8,
        dryMatterPct: 89.5,
        crudeProteinPct: 19.8,
        netEnergyMcal: 1.45,
        purpose: 'ألياف نقية سهلة الهضم تحافظ على نسبة دهن الحليب فوق 3.8%',
      },
      {
        nameAr: 'سيلاج الذرة (Corn Silage)',
        nameEn: 'Corn Silage',
        amountKgDay: 20.0,
        dryMatterPct: 34.0,
        crudeProteinPct: 8.0,
        netEnergyMcal: 1.60,
        purpose: 'قاعدة الطاقة السكرية لتحفيز إنتاج حليب متواصل',
      },
      {
        nameAr: 'كسب الصويا 48% (Soybean Meal)',
        nameEn: 'Soybean Meal',
        amountKgDay: 3.4,
        dryMatterPct: 89.0,
        crudeProteinPct: 48.0,
        netEnergyMcal: 1.95,
        purpose: 'تثبيت مستويات البروتين اليومية',
      },
      {
        nameAr: 'دهون محمية (Bypass Fat)',
        nameEn: 'Rumen-Protected Fat',
        amountKgDay: 0.45,
        dryMatterPct: 99.0,
        crudeProteinPct: 0.0,
        netEnergyMcal: 4.80,
        purpose: 'حماية الوزن الحي والحفاظ على الخصوبة والتلقيح',
      },
    ],
    waterRequirementLitersDay: 135,
    activeCoolingProtocol: {
      mistingIntervalSeconds: 60,
      fanSpeedPct: 85,
      sprinklerFrequencyMinutes: 5,
      nighttimeHyperVentilation: true,
    },
    rumenBufferGramsDay: 220,
  },
  Mila: {
    wilaya: 'Mila',
    thiIndex: 64.3,
    targetDailyYieldL: 40.0,
    ingredients: [
      {
        nameAr: 'دريس البرسيم الحجازي (Alfalfa Hay)',
        nameEn: 'Alfalfa Hay',
        amountKgDay: 6.0,
        dryMatterPct: 88.0,
        crudeProteinPct: 20.0,
        netEnergyMcal: 1.46,
        purpose: 'عليقة قياسية متوازنة في مناخ الهضاب المعتدل',
      },
      {
        nameAr: 'سيلاج الذرة (Corn Silage)',
        nameEn: 'Corn Silage',
        amountKgDay: 22.0,
        dryMatterPct: 35.0,
        crudeProteinPct: 8.4,
        netEnergyMcal: 1.64,
        purpose: 'طاقة متوازنة لدعم إنتاج يفوق 40 لتر/يوم',
      },
      {
        nameAr: 'كسب الصويا والذرة المطحونة (Soy & Ground Corn)',
        nameEn: 'Soybean Meal & Ground Grain',
        amountKgDay: 4.2,
        dryMatterPct: 89.0,
        crudeProteinPct: 34.0,
        netEnergyMcal: 1.98,
        purpose: 'تغذية ذروة الإدرار للأبقار عالية الإنتاجية',
      },
    ],
    waterRequirementLitersDay: 105,
    activeCoolingProtocol: {
      mistingIntervalSeconds: 120,
      fanSpeedPct: 50,
      sprinklerFrequencyMinutes: 15,
      nighttimeHyperVentilation: false,
    },
    rumenBufferGramsDay: 150,
  },
};

export const INITIAL_QR_PASSPORTS: QrPassportPayload[] = [
  {
    token: 'PASSPORT-DZ-ADR-20260927-TANK01',
    batchId: 'SOL-BATCH-DZ-2026-0927-MK01',
    productType: 'Raw A-Grade Milk (حليب خام ممتاز)',
    cowRfidList: ['RFID-CTL-9021', 'RFID-CTL-9022', 'RFID-CTL-9025', 'RFID-CTL-9028'],
    headCountSupplying: 42,
    farmId: 'DZ-FARM-ADRAR-01',
    farmName: 'Adrar Mega-Dairy Oasis Complex (مشروع أدرار الاستراتيجي)',
    farmWilaya: 'Adrar',
    farmCoordinates: [27.9124, -0.2241],
    airliftShipmentNumber: 'SOL-AF-109-TX01',
    usdaHealthCertReference: 'USDA-APHIS-2026-DZ-TX901',
    milkingTimestamp: '2026-09-27T05:30:00Z',
    volumeLiters: 1540.0,
    labAnalysis: {
      fatPercentage: 3.86,
      proteinPercentage: 3.28,
      lactosePercentage: 4.82,
      phValue: 6.66,
      acidityDornic: 15.2,
      somaticCellCount: 108000,
      antibioticResidue: 'Negative (خالٍ من المضادات الحيوية)',
      aflatoxinM1: '< 0.05 ppb (EU/DZ Standard)',
    },
    coldChainTemperatureC: 3.6,
    destinationDairyPlant: 'GIPLAIT Complex / Baladna Dairy Processing Unit',
    hmacSignature: 'a89f920bc4728ef19c011e48bc02a99148db92410ef73a980c6114bc9081bc12',
    issuedAt: '2026-09-27T07:15:00Z',
  },
];
